### ISSUE TITLE
Add `cachePromiseRejection` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-memoize#11]
It was dropped from `mem`: https://github.com/sindresorhus/mem/pull/43

See https://github.com/sindresorhus/p-memoize/issues/3#issuecomment-552364724 first, if you want to work on this.

**Comment by fregante** [comment]
Best if this is done first: https://github.com/sindresorhus/p-memoize/issues/3#issuecomment-552364724

> Now that https://github.com/sindresorhus/mem/pull/43 is in and `mem` has been simplified, this can finally be done.
> 
> PR welcome on `p-memoize` to **copy** `mem` in its entirety (docs and tests), plus:
> 
> - `await` the `.has` and `.get` calls as suggested in https://github.com/sindresorhus/p-memoize/issues/3#issuecomment-506799992
> - restore the `cachePromiseRejection` option
> - update the docs and tests to include `async` examples
