### ISSUE TITLE
Maybe deprecate in favour of mem?

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/p-memoize#2]
It seems like this module now has the exact same behaviour as `mem` 2.0.0, and thus I guess that the need for it has run out since it simply wraps that module. Should we deprecate this module or am I missing something?

Cheers 🍻

**Comment by sindresorhus** [comment]
Closing this as we're going a different direction with this one as we can benefit from it being async-only, which `mem` is not. See #3. I'll make sure to document the differences clearly when #3 is done.
