### ISSUE TITLE
4.0.2 is broken?

### ISSUE THREAD

**Issue by henhal** [sindresorhus/p-memoize#29]
Am I mistaken, or are all releases between 4.0.2 up to 6.0.0 broken?
I was running 4.0.1 for a long time in production with good results, but today when measuring some caching metrics I realized I had lots of misses. Turns out [this commit](https://github.com/sindresorhus/p-memoize/commit/49a4db95a695e195ac37321972278fb633f44be7) breaks the caching of promises by calling `await` on the returned promise _before_ putting it in the cache. Am I right?
I realize this is not a big deal since it IS fixed in 6.0.0, but perhaps put a note on the Readme or something to stay away from 4.0.2 and 5.x? Can you even revert the 4.0.2 release so that ^4.0.1 in package.json does not pick it up?

(BTW I had severe problems going to 6.0 due to the ESM change. I can't for my life get tsconfig to play ball when this module uses ESM. Still struggling...)

**Comment by sindresorhus** [comment]
> (BTW I had severe problems going to 6.0 due to the ESM change. I can't for my life get tsconfig to play ball when this module uses ESM. Still struggling...)

It will be much better with the upcoming TS 4.5: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/

**Comment by henhal** [comment]
Thanks.

Since I found this by chance and it impacted my network performance significantly, do you think it would be good to unpublish 4.0.2? Sure, that will break some installs, but it's better to go back to 4.0.1 if you're on ^4.

At least, wiser from this, I've now added caching metrics to my code to keep track on the hit rate, so there's some good out of this. :)

**Comment by sindresorhus** [comment]
It's not possible to remove versions, but I have deprecated 4.0.2 with a message to stay on 4.0.1 or upgrade to 5.0.0.

**Comment by sindresorhus** [comment]
@fregante Why is it unfortunate? People that don't have a lockfile get notified that they're running on a broken version.

**Comment by fregante** [comment]
Who reads npm install logs? They're so noisy. Leaving a broken version as HEAD of v4 is not great practice, especially if the solution is just republishing 4.0.1 as 4.0.3 (even if breaking for the 1 user who depends on the new behavior, it's not breaking for literally everyone else)

**Comment by niksy** [comment]
@sindresorhus is it possible to backport fixes from https://github.com/sindresorhus/p-memoize/commit/343ac6e71a77031a69f9e52bf03ea40e1cfdcbc8 to 4.0.3?

I agree with @fregante, people rarely read through all install logs, and just switching to >= 5.0.0 is not convenient for projects where ESM is not fully embraced.

**Comment by sindresorhus** [comment]
> and just switching to >= 5.0.0 is not convenient for projects where ESM is not fully embraced.

You can use `await import('p-memoize')` from CommonJS.

**Comment by sindresorhus** [comment]
@fregante I don't disagree, but there's also a risk to just revert to 4.0.1.

Would backporting https://github.com/sindresorhus/p-memoize/commit/343ac6e71a77031a69f9e52bf03ea40e1cfdcbc8 work for anyone? That seems like a less risky change.

**Comment by niksy** [comment]
> > and just switching to >= 5.0.0 is not convenient for projects where ESM is not fully embraced.
> 
> You can use `await import('p-memoize')` from CommonJS.

Right, but that works only for Node >= 12 if I’m correct?

> @fregante I don't disagree, but there's also a risk to just revert to 4.0.1.
> 
> Would backporting [343ac6e](https://github.com/sindresorhus/p-memoize/commit/343ac6e71a77031a69f9e52bf03ea40e1cfdcbc8) work for anyone? That seems like a less risky change.

This seems like reasonable solution. We would need ponyfill (or basic implementation) for `Promise.allSettled` to cover Node <= 12.9.0.

**Comment by sindresorhus** [comment]
> Right, but that works only for Node >= 12 if I’m correct?

Node.js 14. So it's a good solution if you're not making reusable packages.

**Comment by niksy** [comment]
I’ve created [PR](https://github.com/sindresorhus/p-memoize/pull/37) for this. https://github.com/sindresorhus/p-memoize/commit/343ac6e71a77031a69f9e52bf03ea40e1cfdcbc8 has been cherry-picked and I’ve used `p-settle` for `Promise.allSettled` implementation.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-memoize/releases/tag/v4.0.3
