### ISSUE TITLE
An option to wait for `cache.set` to resolve before resolving the returned promise (or even make this the default behavior)

### ISSUE THREAD

**Issue by futpib** [sindresorhus/p-memoize#34]
One can bypass cache by making multiple consecutive calls with the same arguments:

```ts
// Imagine a custom `cache` with a slow `cache.set` and a fast `cache.has`
await memoized('foo'); // Calls `cache.set('foo', 'bar')`
// First `cache.set('foo', 'bar')` promise did not resolve yet and `cache.has('foo')` will resolve to `false`
await memoized('foo'); // Calls `cache.set('foo', 'bar')` again
// Some time later...
// First `cache.set('foo', 'bar')` promise resolved
// Only now will `cache.has('foo')` resolve to `true`
// Second `cache.set('foo', 'bar')` promise resolved but it should not have been called in the first place
```

https://github.com/sindresorhus/p-memoize/blob/e8574a1047910e8940ce8d7fa6bea4cf18bc4567/index.ts#L122

See this PR for a test that demonstrates this https://github.com/sindresorhus/p-memoize/pull/35
See this PR for a head-on fix (breaking change) that awaits all cache operations https://github.com/sindresorhus/p-memoize/pull/36

**Comment by Richienb** [comment]
@sindresorhus

- If we check `promiseCache` for a pending call first, [values that are removed from `cache` by external means are not picked up on](https://github.com/sindresorhus/p-memoize/issues/31).
- If we check `cache` first, the `promiseCache` becomes useless since there is already a value in `cache` which causes this issue.

**Comment by Richienb** [comment]
Even if we did await all `set` calls, behold this simple example:

```js
await Promise.all([
	memoized('foo'),
	memoized('foo'),
]);
```

**Comment by sindresorhus** [comment]
^ @futpib Any opinion?

It's unclear to me what the best way forward here is.

**Comment by Richienb** [comment]
@sindresorhus Solved it by caching the entire asynchronous part of the `pMemoize` function rather than just the promise returned by the memoized function. See #48.
