### ISSUE TITLE
Clarification about maxAge vs expiry-map based time-based cache expiration

### ISSUE THREAD

**Issue by mathiasm74** [sindresorhus/p-memoize#38]
Why is there a whole section in the README.md describing how to use expiry-map to achieve time-based cache expiration when the much-easier-to-use maxAge option seems to work just as well? 

And why is the maxAge option only mentioned in the vaguest of terms?

**Comment by sindresorhus** [comment]
The `maxAge` option was removed in v6: https://github.com/sindresorhus/p-memoize/releases/tag/v6.0.0
