### ISSUE TITLE
Option to limit concurrent invocations?

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/p-memoize#43]
Hi! Is it possible to use p-memoize to optimistically memoize promises when several are kicked off before any results have come back? Here's the scenario we're hitting:

```ts
const getData = async params => {
  const data = await getDataFromSomeAPI(params) // quite slow
  return data.foo
}

export default pMemoize(getData, { cacheKey: JSON.stringify })
```

This function is on our server side and ends up being hit by next.js as part of static-site generation (and during [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration)). But what this means is that it gets hit hundreds of times simultaneously, once per page that's being generated. The API we're using has a pretty aggressive rate limit, so we're aiming to use pMemoize to get around that, since all of the pages hit the backend with the same parameters.

The workaround we're trying now:

```ts
import pMemoize from 'p-memoize'
import pLimit from 'p-limit'

const memoize = (fn, options) => {
  const getLimiter = pMemoize(async (...args) => pLimit(1), { cacheKey: JSON.stringify })
  const memoized = pMemoize(fn, {cacheKey: JSON.stringify, ...options})
  return (async (...args) => {
    const limiter = await getLimiter(...args)
    return limiter(async () => memoized(...args))
  })
}
```

Effectively, this means that memoizable calls will wait until the "first" attempt has settled, and use the memoized result if it succeeded. If the first attempt failed they'll run the full funciton.

Which seems to work, but is pretty awkward to write and involves adding the `p-limit` dependency manually. Is there a better/recommended way of doing this? If not, maybe there could be an extra option for it?

**Comment by sindresorhus** [comment]
I believe this is how it was working before https://github.com/sindresorhus/p-memoize/pull/32.

Also see: https://github.com/sindresorhus/p-memoize/issues/34

**Comment by Richienb** [comment]
Your use case appears to be default behaviour now as of v7.

**Comment by mmkal** [comment]
Ok, great. Not quite ready to upgrade and can reopen or make a new issue when I try it out
