### ISSUE TITLE
Move `type-fest` to development dependencies

### ISSUE THREAD

**Issue by mahnunchik** [sindresorhus/p-memoize#54]
I think it is better to move `type-fest` module to development dependencies.

Motivation: it doesn't required in compiled `.js` file.

And I don't need typescipt in my application in production:

```
└─┬ p-memoize@7.1.1
  └─┬ type-fest@3.10.0
    └── typescript@5.0.4
```

**Comment by sindresorhus** [comment]
The type is used in production, so that would be a mistake. As for the `typescript` thing, see: https://github.com/sindresorhus/p-memoize

**Comment by mahnunchik** [comment]
Ok, got it, typescript is cancer on the body of modern js.
